#+title: SYSC3010 Group Project
* Table of Contents                                          :TOC_1:noexport:
- [[#links][Links]]
- [[#symptom-monitoring-door-system][Symptom monitoring Door System]]
- [[#group-expectations][Group Expectations]]
- [[#group-roles][Group Roles]]

* Links
- [[file:meeting-notes.org][Meeting Notes]]

* Symptom monitoring Door System
** Terminology
To keep a consistent style please use the following terms. No synonyms please
- Door Node
- Control Server
  - Users have: Accounts
- Security Badge
- NFC security badge reader
- infrared temperature sensor
- electronic lock actuator
** Description
The purpose of this system is to increase security and safety of
secured locations, like offices. The system will attempt to prevent
the spread of illness by limiting the number of people which can enter
the building, and by preventing people with a high body temperature
from entering the building.

This system will be mounted on the entrances and exits of a
building. The system will be modular to allow an arbitrary number of
nodes to be added.

The system will display a green light at the entrance if it is
accepting people. The light will turn red when the area is closed or
if there are too many people inside.

If the light is green, the user will present their NFC security card
to the system. The system send a message containing a unique user ID
to a server. The server will use it'd database to determine if the
user is authorized and if the user had previously shown symptoms to
the system within the last 14 days. The server will then notify the
door with the results of the query.

If the user has not already been denied, the system will then take the
user's temperature. If the temperature is above the threshold, they
can try again in 1 minute. If they fail 3 times in a row, they will be
forbidden access, and the operator of the system will have the option
to automatically deny them entry for the duration of a quarantine
period.

Every access attempt, including the associated temperature reading and
user ID, is sent to the server to be logged in a database.

If the temperature is below the threshold, and they have access, the
door will open.

Users will also have to present their NFC card to the door to leave
the building. By tracking users entering and exiting the building, the
server will know how many people are in the building.

The central server will also provide a GUI available to the buildings
security team. This GUI will allow security officers to manually
update the status of individuals in case a door must fall back to
manual operation. It will also allow the security team to modify who
has access to the building. For example, if someone receives a
negative test result for COVID-19, their access to the building could
be restored.




* Group Expectations
- Slack messages will be responded to within 1 work day.
* Group Roles
** Sam
- Submit deliverables
** Sunny
** Mario
** Morgan
- Meeting Secretary
