#! /usr/bin/env python3

#
# file name: Rangefinder_test
# Description: Rangefinder functional test code for second test demo 
# Author(s): Sunjeevani Pujari
#

import sys
sys.path.append("../../hardware")

import time
from RangeFinder import RangeFinder 

sensor = RangeFinder()

#testing different ranges
print("Testing functionality of Range Finder")
print("Testing different ranges")
i = 0
while (i <= 5):
    activate = True
    dist = sensor.get_range(activate)
    print(f"Range is {dist}")
    i += 1
    time.sleep(3)
print("Range Finder test complete")
